const SCREENS = {
  INTRO: 'INTRO',
  LOGIN: 'LOGIN',
  HOME: 'HOME',
  PROFILE: 'PROFILE',
  FAVORITE: 'FAVORITE',
  ALLSTORE: 'ALLSTORE',
  HOME_STACK: 'HOME_STACK',
  SEATCHSCRENN: 'SEATCHSCRENN',
  PRODUCT_LIST: 'PRODUCT_LIST',
};

export default SCREENS;
