const SCREENS = {
  INTRO: 'INTRO',
  LOGIN: 'LOGIN',
  HOME: 'HOME',
  PROFILE: 'PROFILE',
  FAVORITE: 'FAVORITE',
  ALLSTORE: 'ALLSTORE',
  HOME_STACK: 'HOME_STACK',
  SEATCHSCRENN: 'SEATCHSCRENN',
  PRODUCT_LIST: 'PRODUCT_LIST',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  CART_SCREEN: 'CART_SCREEN',
  ORDER: 'ORDER',
  ORDER_DETAIL: 'ORDER_DETAIL',
  ORDER_HISTORY: 'ORDER_HISTORY',
  ORDER_HISTORY_DETAIL: 'ORDER_HISTORY_DETAIL',
};

export default SCREENS;
