import {StyleSheet} from 'react-native';
import {COLORS} from '../../../../constants';
export default StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: COLORS.WHITE || '#fff',
    marginTop: 30,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    zIndex: 1,
  },
  headerText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.BLACK || '#1A1A1A',
  },
  container: {
    padding: 15,
    paddingTop: 60,
    paddingBottom: 40,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.DARK || '#333',
    marginBottom: 8,
  },
  input: {
    backgroundColor: COLORS.WHITE || '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: COLORS.BLACK || '#1A1A1A',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
  },
  disabledInput: {
    backgroundColor: COLORS.DISABLED || '#F5F5F5',
    color: COLORS.DISABLED_TEXT || '#666',
  },
  multilineInput: {
    height: 100,
    textAlignVertical: 'top',
  },
  selectionPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 8,
    padding: 12,
    backgroundColor: COLORS.WHITE || '#FFFFFF',
  },
  selectionPickerSelected: {
    borderColor: COLORS.PRIMARY || '#00C853',
  },
  selectionPickerText: {
    fontSize: 16,
    color: COLORS.PLACEHOLDER || '#A0A0A0',
  },
  selectionPickerTextSelected: {
    color: COLORS.BLACK || '#1A1A1A',
  },
  imagePicker: {
    borderRadius: 8,
    backgroundColor: COLORS.WHITE || '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
  },
  imageContainer: {
    position: 'relative',
    alignItems: 'center',
  },
  imagePlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePickerText: {
    color: COLORS.SECONDARY || '#666',
    fontSize: 14,
    marginTop: 8,
  },
  imagePreview: {
    width: 100,
    height: 100,
    borderRadius: 8,
    resizeMode: 'contain',
  },
  deleteButton: {
    position: 'absolute',
    top: -10,
    right: -10,
    backgroundColor: COLORS.WHITE || '#FFFFFF',
    borderRadius: 12,
    padding: 2,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  updateButton: {
    backgroundColor: COLORS.PRIMARY || '#00C853',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    flex: 1,
    marginRight: 10,
  },
  deleteStoreButton: {
    backgroundColor: COLORS.ERROR || '#FF0000',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    flex: 1,
  },
  submitButtonDisabled: {
    backgroundColor: COLORS.DISABLED || '#A0A0A0',
    opacity: 0.7,
  },
  submitButtonText: {
    color: COLORS.WHITE || '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
